<a href="https://colab.research.google.com/github/Maitreyi12/maitreyiR/blob/main/numpy_assignment_code_kong.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy assignment

## 1. Import numpy 

In [1]:
import numpy as np

## 2. Create an array of 10 zeroes

In [2]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 3. Create an array of 10 ones

In [3]:
import numpy as np
array=np.ones(10)
print("An array of 10 ones:")
print(array)

An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## 4. Create an array of 10 fives

In [4]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of integers from 11 to 50

In [6]:
import numpy as np
array=np.arange(11,51,1)
print("Array of all the integers from 11 to 50")
print(array)

Array of all the integers from 11 to 50
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


## 6. Create an array of all the even integers from 11 to 50

In [8]:
import numpy as np
array=np.arange(12,50,2)
print("Array of all the even integers from 11 to 50")
print(array)

Array of all the even integers from 11 to 50
[12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


## 7. Create a 3 * 3 matrices of values from range 0 to 8 

In [9]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Use numpy to gentrate a number randomly between 0 and 1

In [10]:
import numpy as np
rand_num = np.random.normal(0,1,1)
print("Random number between 0 and 1:")
print(rand_num)

Random number between 0 and 1:
[-2.04392394]


## Create the following matrices

### 20 linrarly spaced points between 0 and 2

In [11]:
np.linspace(0, 2, 20)

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

## Numpy indexing and selection

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Use the above matrices for the following set of questions

### 1. only first value of matrice mat

In [28]:
mat = np.arange(1,26).reshape(5,5)
mat[0,0]

1

### 2. middle value of matrice mat

In [48]:
mat = np.arange(1,26).reshape(5,5)
mat[:3,:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

### 3. first two rows and last one column values of matrice mat

In [71]:
mat = np.arange(1,26).reshape(5,5)
mat[4:5,0:2]

array([[21, 22]])

### 4. last row and all column values of matrice mat

In [76]:
mat = np.arange(1,26).reshape(5,5)
mat[0:5,4:5]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])